FROM ubuntu:latest
    
RUN apt update && \
    apt install -y --no-install-recommends \
        postfix \
        dovecot-core \
        dovecot-imapd \
        dovecot-pop3d \
        net-tools

COPY main.cf /etc/postfix/
COPY dovecot.conf /etc/dovecot/

EXPOSE 25 110

CMD /usr/sbin/postfix start && /usr/sbin/dovecot -F
