version: "3"
services:
  soa:
    build:
      context: soa/
      dockerfile: dockerfile
    ports:
      - 54:53
    networks:
      dmz:
        ipv4_address: 10.0.0.20

  dns:
    build:
      context: dns/
      dockerfile: dockerfile
    ports:
      - 53:53
    networks:
      trusted:
        ipv4_address: 10.0.0.2

networks:
  dmz:
    driver: bridge
    ipam:
        config:
            - subnet: 10.0.0.0/28
  trusted:
    driver: bridge
    ipam:
        config:
            - subnet: 10.0.0.16/28
