version: "3"
services:
  # ---------------
  #  DMZ
  # ---------------
  soa:
    build:
      context: dns/soa/
      dockerfile: dockerfile
    networks:
      dmz:
        ipv4_address: 172.42.0.14
      trusted:
      zone1:
    ports:
      - "53:53/udp"
    dns:
      - 172.42.0.28
  # ---------------
  web_pub:
    build:
      context: web/public
      dockerfile: Dockerfile
    networks:
      dmz:
        ipv4_address: 172.42.0.13
      trusted:
      zone1:
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    dns:
      - 172.42.0.28
  # ---------------
  mta:
    build:
      context: mail/proxy/
      dockerfile: dockerfile
    networks:
      dmz:
        ipv4_address: 172.42.0.12
      trusted:
      zone1:
    # ports:
    #   - "49300:25"
    #   - "49400:110"
    dns:
      - 172.42.0.28

  # ---------------
  #  Trusted
  # ---------------
  web:
    build:
      context: web/intranet
      dockerfile: Dockerfile
    networks:
      trusted:
        ipv4_address: 172.42.0.30
      dmz:
      zone1:
    # ports:
    #   - "49500:443"
    dns:
      - 172.42.0.28
  # ---------------
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: clients
    volumes:
      - database:/docker-entrypoint-initdb.d
    networks:
      trusted:
        ipv4_address: 172.42.0.29
      dmz:
      zone1:
    # ports:
    #   - "49600:3306"
    dns:
      - 172.42.0.28
  # ---------------
  dns:
    build:
      context: dns/resolver/
      dockerfile: dockerfile
    networks:
      trusted:
        ipv4_address: 172.42.0.28
      dmz:
      zone1:
    # ports:
    #   - "49700:53"
    dns:
      - 172.42.0.28
  # ---------------
  mail_internal:
    build:
      context: mail/internal/
      dockerfile: dockerfile
    networks:
      trusted:
        ipv4_address: 172.42.0.27
      dmz:
      zone1:
    # ports:
    #   - "49800:110"
    #   - "49900:25"
    dns:
      - 172.42.0.28
  # ---------------
  #  Users
  # ---------------
  pc:
    build:
      context: pc/
      dockerfile: dockerfile
    networks:
      zone1:
        ipv4_address: 172.42.1.35
      dmz:
      trusted:
    dns:
      - 172.42.0.28

# NETWORKS ==============================================
networks:
  dmz:
    driver: bridge
    ipam:
      config:
        - subnet: 172.42.0.0/28
  trusted:
    driver: bridge
    ipam:
      config:
        - subnet: 172.42.0.16/28
  zone1:
    driver: bridge
    ipam:
      config:
        - subnet: 172.42.1.0/24

volumes:
  database:
