version: "3"
services:
  # ---------------
  #  DMZ
  # ---------------
  soa:
    build:
      context: dns/soa/
      dockerfile: dockerfile
    ports:
      - "49200:53"
    networks:
      dmz:
        ipv4_address: 172.42.0.2
      trusted:
      zone1:
    dns:
      - 172.42.0.20

  # ---------------
  #  web (public)
  # ---------------
  mta:
    build:
      context: mail/MTA/
      dockerfile: dockerfile
    ports:
      - "49300:25"
      - "49400:110"
    networks:
      dmz:
        ipv4_address: 172.42.0.4
      trusted:
      zone1:
    dns:
      - 172.42.0.20

  # ---------------
  #  Trusted
  # ---------------
  web:
    build:
      context: web/intranet
      dockerfile: Dockerfile
    ports:
      - "49500:443"
    networks:
      trusted:
        ipv4_address: 172.42.0.18
      dmz:
      zone1:
    dns:
      - 172.42.0.20

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: clients
    volumes:
      - database:/docker-entrypoint-initdb.d
    ports:
      - "49600:3306"
    networks:
      trusted:
        ipv4_address: 172.42.0.19
      dmz:
      zone1:
    dns:
      - 172.42.0.20

  # ---------------
  dns:
    build:
      context: dns/resolver/
      dockerfile: dockerfile
    ports:
      - "49700:53"
    networks:
      trusted:
        ipv4_address: 172.42.0.20
      dmz:
      zone1:
    dns:
      - 172.42.0.20

  # ---------------
  mda:
    build:
      context: mail/MDA/
      dockerfile: dockerfile
    ports:
      - "49800:110"
      - "49900:25"
    networks:
      trusted:
        ipv4_address: 172.42.0.21
      dmz:
      zone1:
    dns:
      - 172.42.0.20

  # ---------------
  #  Users
  # ---------------
  pc:
    build:
      context: pc/
      dockerfile: dockerfile
    networks:
      zone1:
        ipv4_address: 172.42.1.35
      dmz:
      trusted:
    dns:
      - 172.42.0.20

# NETWORKS ==============================================
networks:
  dmz:
    driver: bridge
    ipam:
      config:
        - subnet: 172.42.0.0/28
  trusted:
    driver: bridge
    ipam:
      config:
        - subnet: 172.42.0.16/28
  zone1:
    driver: bridge
    ipam:
      config:
        - subnet: 172.42.1.0/24

volumes:
  database: