version: "3"
services:
  # ---------------
  #  DMZ
  # ---------------
  soa:
    build:
      context: dns/soa/
      dockerfile: dockerfile
    networks:
      dmz:
        ipv4_address: 172.42.0.2
    dns:
      - 172.42.0.20
  # ---------------
      # web (public)
  # ---------------
  mta:
    build:
      context: mail/MTA/
      dockerfile: dockerfile
    networks:
      dmz:
        ipv4_address: 172.42.0.4
    dns:
      - 172.42.0.20

  # ---------------
  #  Trusted
  # ---------------
  web:
    build:
      context: web/intranet
      dockerfile: Dockerfile
    networks:
      trusted:
        ipv4_address: 172.42.0.18
    dns:
      - 172.42.0.20
  # ---------------
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: clients
    volumes:
      - database:/docker-entrypoint-initdb.d
    networks:
      trusted:
        ipv4_address: 172.42.0.19
    dns:
      - 172.42.0.20
  # ---------------
  dns:
    build:
      context: dns/resolver/
      dockerfile: dockerfile
    networks:
      trusted:
        ipv4_address: 172.42.0.20
    dns:
      - 172.42.0.20
  # ---------------
  mda:
    build:
      context: mail/MDA/
      dockerfile: dockerfile
    networks:
      trusted:
        ipv4_address: 172.42.0.21
    dns:
      - 172.42.0.20
  # ---------------
  #  Users
  # ---------------
  pc:
    build:
      context: pc/
      dockerfile: dockerfile
    networks:
      zone1:
        ipv4_address: 172.42.1.35
    dns:
      - 172.42.0.20

# NETWORKS ==============================================
networks:
  dmz:
    driver: ipvlan
    ipam:
      config:
        - subnet: 172.42.0.0/28
    driver_opts:
      ipvlan_mode: l3
      parent: eth0.1
  trusted:
    driver: ipvlan
    ipam:
      config:
        - subnet: 172.42.0.16/28
    driver_opts:
      ipvlan_mode: l3
      parent: eth0.2
  zone1:
    driver: ipvlan
    ipam:
      config:
        - subnet: 172.42.1.0/24
    driver_opts:
      ipvlan_mode: l3
      parent: eth0.4

volumes:
  database:
