version: "3"
services:
  # ---------------
  #  DMZ
  # ---------------
  soa:
    build:
      context: dns/soa/
      dockerfile: dockerfile
    networks:
      global:
        ipv4_address: 172.16.0.2
    dns:
      - 172.16.0.20
  # ---------------
  dns:
    build:
      context: dns/resolver/
      dockerfile: dockerfile
    networks:
      global:
        ipv4_address: 172.16.0.20
    dns:
      - 172.16.0.20

  # ---------------
  #  Trusted
  # ---------------
  web:
    build:
      context: web/
      dockerfile: Dockerfile
    networks:
      global:
        ipv4_address: 172.16.0.17
    dns:
      - 172.16.0.20
  # ---------------
  mda:
    build:
      context: mail/MDA/
      dockerfile: dockerfile
    networks:
      global:
        ipv4_address: 172.16.0.21
    dns:
      - 172.16.0.20
  # ---------------
  #  Users
  # ---------------
  pc:
    build:
      context: pc/
      dockerfile: dockerfile
    networks:
      global:
        ipv4_address: 172.16.1.35
    dns:
      - 172.16.0.20

# NETWORKS ==============================================
networks:
  global:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.0.0/16

# networks:
#   dmz:
#     driver: bridge
#     ipam:
#       config:
#         - subnet: 10.0.0.0/28
#   trusted:
#     driver: bridge
#     ipam:
#       config:
#         - subnet: 10.0.0.16/28
#   zone1:
#     ipam:
#       config:
#         - subnet: 10.1.1.0/24
