FROM nginx
    
RUN apt-get update && apt-get install -y \
    libssl-dev \
    build-essential \
    gcc \
    libpcre3 \
    libpcre3-dev \
    zlib1g \
    zlib1g-dev \
    openssl

RUN openssl req -x509 -nodes -days 365 \
    -subj  "/C=CA/ST=QC/O=Company Inc/CN=www.m2-7.ephec-ti.be" \
     -newkey rsa:2048 -keyout /etc/ssl/certs/server.key \
     -out /etc/ssl/certs/server.crt;

RUN curl -LO http://nginx.org/download/nginx-1.19.10.tar.gz && tar -xzf nginx-1.19.10.tar.gz
WORKDIR /nginx-1.19.10
RUN ./configure --with-mail
RUN make && make install

COPY default /etc/nginx/nginx.conf

CMD ["nginx", "-g", "daemon off;"]
