FROM nginx
    
RUN apt-get update && apt-get install -y \
    libssl-dev \
    build-essential \
    gcc \
    libpcre3 \
    libpcre3-dev \
    zlib1g \
    zlib1g-dev
RUN curl -LO http://nginx.org/download/nginx-1.19.10.tar.gz && tar -xzf nginx-1.19.10.tar.gz
WORKDIR /nginx-1.19.10
RUN ./configure --with-mail
RUN make && make install

COPY default /etc/nginx/nginx.conf

CMD ["nginx", "-g", "daemon off;"]
