FROM ubuntu:latest

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        ca-certificates \
        curl \
        wget \
        nano \
        vim-tiny \
        iputils-ping \
        dnsutils \
        ssmtp \
        telnet \
        && rm -rf /var/lib/apt/lists/*
                
COPY .muttrc /home/toto/

CMD ["tail", "-f", "/dev/null"]