FROM ubuntu:latest
    
RUN apt update && \
    DEBIAN_FRONTEND=noninteractive \
    apt install -y --no-install-recommends \
        postfix \
        dovecot-core \
        dovecot-imapd \
        dovecot-pop3d \
        net-tools \
        opendkim \
        opendkim-tools \
        openssl

RUN openssl req -x509 -nodes -days 365 \
    -subj  "/C=CA/ST=QC/O=Company Inc/CN=www.m2-7.ephec-ti.be" \
     -newkey rsa:2048 -keyout /etc/ssl/certs/server.key \
     -out /etc/ssl/certs/server.crt;

COPY opendkim.key /etc/opendkim/opendkim.key
COPY opendkim.pub.key /etc/opendkim/opendkim.pub.key
COPY dkim.conf /etc/opendkim.conf

RUN chmod "u=rw,o=,g=" /etc/opendkim/opendkim.key
RUN chown opendkim:opendkim /etc/opendkim/opendkim.key

COPY main.cf /etc/postfix/
COPY dovecot.conf /etc/dovecot/

COPY createusers.sh /usr/local/bin/
COPY users.txt /

RUN chmod +x /usr/local/bin/createusers.sh

RUN mkdir -p /var/spool/postfix/private && \
    chown postfix:postfix /var/spool/postfix/private && \
    chmod 710 /var/spool/postfix/private && \
    groupadd -g 5000 vmail && \
    useradd -u 5000 -g vmail -d /home/vmail -m vmail && \
    chown -R vmail:vmail /var/mail

RUN createusers.sh

EXPOSE 25 110 143 995 587

CMD /usr/sbin/postfix start && /usr/sbin/dovecot -F
