FROM ubuntu:latest

# Install necessary packages
RUN apt-get update && \
    apt-get install -y \
        postfix \
        dovecot-imapd \
        dovecot-pop3d

# Copy configuration files
COPY main.cf /etc/postfix/
COPY master.cf /etc/postfix/
COPY dovecot.conf /etc/dovecot/

# Expose necessary ports
EXPOSE 25/tcp 143/tcp 993/tcp

# Start Postfix and Dovecot services
CMD ["sh", "-c", "service postfix start && service dovecot start && tail -f /var/log/mail.log"]
