FROM ubuntu:latest

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        ca-certificates \
        curl \
        wget \
        nano \
        vim-tiny \
        && rm -rf /var/lib/apt/lists/*
    
RUN apt update
RUN apt install -y bind9 bind9utils bind9-doc dnsutils
RUN wget --user=ftp --password=ftp ftp://ftp.rs.internic.net/domain/db.cache -O /etc/bind/db.root

COPY named.conf /etc/bind/

EXPOSE 53/udp

CMD ["named", "-g"]
